# Generated by Django 3.2.4 on 2021-06-06 21:12

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Jobs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('job_category', models.CharField(choices=[('IT - Software / Hardware / Networking', 'IT - Software / Hardware / Networking'), ('Business / Administration', 'Business / Administration'), ('Engineering', 'Engineering'), ('Marketing / Sales ', 'Marketing / Sales '), ('Medical / Healthcare', 'Medical / Healthcare'), ('Accounts / Finance', 'Accounts / Finance'), ('Education / Course / Language', 'Education / Course / Language'), ('Other', 'Other')], max_length=255)),
                ('position', models.CharField(max_length=255)),
                ('Experience', models.CharField(max_length=255)),
                ('job_description', models.TextField()),
                ('responsiblities', models.TextField()),
                ('skill', models.TextField()),
                ('education', models.CharField(max_length=255)),
                ('what_we_offer', models.TextField()),
                ('email', models.CharField(max_length=255)),
                ('post_date', models.DateField(auto_now_add=True)),
                ('before_date', models.DateField()),
                ('post_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['post_date'],
            },
        ),
    ]
