# Generated by Django 3.2.4 on 2021-06-10 00:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Jobs', '0009_remove_jobs_experience'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='jobs',
            options={},
        ),
        migrations.RemoveField(
            model_name='jobs',
            name='before_date',
        ),
        migrations.RemoveField(
            model_name='jobs',
            name='education',
        ),
        migrations.RemoveField(
            model_name='jobs',
            name='email',
        ),
        migrations.RemoveField(
            model_name='jobs',
            name='job_category',
        ),
        migrations.RemoveField(
            model_name='jobs',
            name='job_description',
        ),
        migrations.RemoveField(
            model_name='jobs',
            name='position',
        ),
        migrations.RemoveField(
            model_name='jobs',
            name='post_date',
        ),
        migrations.RemoveField(
            model_name='jobs',
            name='responsiblities',
        ),
        migrations.RemoveField(
            model_name='jobs',
            name='skill',
        ),
        migrations.RemoveField(
            model_name='jobs',
            name='what_we_offer',
        ),
    ]
