# Generated by Django 3.2.4 on 2021-06-10 11:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Jobs', '0019_auto_20210610_1109'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobs',
            name='before_date',
            field=models.DateField(blank=True, default='2020-2-2', null=True),
        ),
        migrations.AlterField(
            model_name='jobs',
            name='post_date',
            field=models.DateField(auto_now_add=True, null=True),
        ),
    ]
