# Generated by Django 3.2.4 on 2021-06-10 13:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Jobs', '0021_auto_20210610_1336'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobs',
            name='before_date',
            field=models.DateTimeField(default='2020-2-2'),
        ),
        migrations.AlterField(
            model_name='jobs',
            name='post_date',
            field=models.DateTimeField(default='2020-2-2'),
        ),
    ]
