# Generated by Django 3.2.4 on 2021-06-10 17:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Jobs', '0022_auto_20210610_1337'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobs',
            name='before_date',
            field=models.DateField(default='2020-2-2'),
        ),
    ]
