# Generated by Django 3.2.4 on 2021-06-10 17:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Jobs', '0023_alter_jobs_before_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobs',
            name='post_date',
            field=models.DateField(default='2020-2-2'),
        ),
    ]
