# Generated by Django 3.2.4 on 2021-06-12 17:49

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Jobs', '0029_auto_20210612_1747'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobs',
            name='post_by',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
