# Generated by Django 3.2.4 on 2021-06-15 02:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Jobs', '0035_auto_20210614_0827'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobs',
            name='days_left',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
