# Generated by Django 3.2.4 on 2021-06-05 19:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CompanyRegistrationModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=255)),
                ('contact_number', models.CharField(blank=True, max_length=255)),
                ('password', models.CharField(max_length=255)),
                ('password1', models.CharField(max_length=255)),
                ('logo', models.ImageField(blank=True, upload_to='logo/')),
                ('place', models.CharField(choices=[('Kathmandu', 'Kathmandu'), ('Pokhara', 'Pokhara'), ('Lalitpur', 'Lalitpur'), ('Bharatpur', 'Bharatpur'), ('Biratnagar', 'Biratnagar'), ('Janakpur', 'Janakpur'), ('Ghorahi', 'Ghorahi'), ('Hetauda', 'Hetauda'), ('Dhangadhi', 'Dhangadhi'), ('Tulsipur', 'Tulsipur'), ('Itahari', 'Itahari'), ('Nepalgunj', 'Nepalgunj'), ('Butwal', 'Butwal'), ('Dharan', 'Dharan'), ('Kalaiya', 'Kalaiya'), ('Jitpursimara', 'Jitpursimara'), ('Other', 'Other')], max_length=255)),
            ],
        ),
    ]
