# Generated by Django 3.2.4 on 2021-06-10 00:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Jobs', '0008_remove_jobs_post_by'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='jobs',
            name='experience',
        ),
    ]
