# Generated by Django 3.2.4 on 2021-06-10 11:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Jobs', '0018_alter_jobs_post_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobs',
            name='before_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='jobs',
            name='post_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
