# Generated by Django 3.2.4 on 2021-06-10 22:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Jobs', '0026_test'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Test',
        ),
        migrations.AlterModelOptions(
            name='jobs',
            options={},
        ),
        migrations.AddField(
            model_name='jobs',
            name='location',
            field=models.CharField(choices=[('Kathmandu', 'Kathmandu'), ('Pokhara', 'Pokhara'), ('Lalitpur', 'Lalitpur'), ('Bharatpur', 'Bharatpur'), ('Biratnagar', 'Biratnagar'), ('Janakpur', 'Janakpur'), ('Ghorahi', 'Ghorahi'), ('Hetauda', 'Hetauda'), ('Dhangadhi', 'Dhangadhi'), ('Tulsipur', 'Tulsipur'), ('Itahari', 'Itahari'), ('Nepalgunj', 'Nepalgunj'), ('Butwal', 'Butwal'), ('Dharan', 'Dharan'), ('Kalaiya', 'Kalaiya'), ('Jitpursimara', 'Jitpursimara'), ('Other', 'Other')], default='', max_length=255),
        ),
    ]
