# Generated by Django 3.2.4 on 2021-06-12 17:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Jobs', '0027_auto_20210610_2205'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobs',
            name='company_name',
            field=models.CharField(default='', max_length=255),
        ),
    ]
