# Generated by Django 3.2.4 on 2021-06-12 17:53

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Jobs', '0031_alter_jobs_post_by'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobs',
            name='post_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
