# Generated by Django 3.2.4 on 2021-06-14 08:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Jobs', '0033_hitcount'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobs',
            name='job_type',
            field=models.CharField(choices=[('Full Time', 'Full Time'), ('Part Time', 'Part Time'), ('Contract', 'Contract')], default='', max_length=255),
        ),
        migrations.AddField(
            model_name='jobs',
            name='number_of_vacancy',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AddField(
            model_name='jobs',
            name='position_type',
            field=models.CharField(choices=[('Entry Level', 'Entry Level'), ('Intermediate', 'Intermediate'), ('Expert', 'Expert')], default='', max_length=255),
        ),
        migrations.AddField(
            model_name='jobs',
            name='salary',
            field=models.CharField(default='', max_length=255),
        ),
    ]
