# Generated by Django 3.2.4 on 2021-06-15 03:38

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('Jobs', '0036_jobs_days_left'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobs',
            name='post_date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
